# Generated by Django 4.2.7 on 2025-11-16 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_functions_text_function_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, help_text='Brief description about yourself', null=True)),
                ('current_title', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('portfolio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_types', models.CharField(blank=True, help_text='Comma-separated employment types', max_length=255)),
                ('preferred_locations', models.TextField(blank=True, help_text='Comma-separated locations')),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('remote_only', models.BooleanField(default=False)),
                ('minimum_salary', models.CharField(blank=True, choices=[('0-50k', '$0 - $50,000'), ('50k-75k', '$50,000 - $75,000'), ('75k-100k', '$75,000 - $100,000'), ('100k-150k', '$100,000 - $150,000'), ('150k-200k', '$150,000 - $200,000'), ('200k+', '$200,000+')], max_length=20, null=True)),
                ('industries', models.TextField(blank=True, help_text='Comma-separated industries')),
                ('company_size_preference', models.CharField(blank=True, help_text='e.g., Startup, Mid-size, Enterprise', max_length=255)),
                ('email_notifications', models.BooleanField(default=True)),
                ('job_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired_functions', models.ManyToManyField(blank=True, related_name='job_seekers', to='companies.function')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preference', to=settings.AUTH_USER_MODEL)),
                ('work_environments', models.ManyToManyField(blank=True, related_name='job_seekers', to='companies.workenvironment')),
            ],
            options={
                'verbose_name': 'Job Preference',
                'verbose_name_plural': 'Job Preferences',
            },
        ),
    ]
