# Generated by Django 4.2.7 on 2025-11-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpreference',
            name='actively_looking',
            field=models.BooleanField(default=False, help_text='User is actively looking for job opportunities'),
        ),
    ]
