# Generated by Django 4.2.7 on 2026-05-18 04:29

from django.db import migrations, models


def create_default_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('accounts', 'EmailTemplate')
    templates = {
        'account_created': {
            'name': 'New account creation',
            'subject': 'Welcome to WhoIsHiringInTech',
            'html_body': '<p>Hi {{ first_name|default:"there" }},</p><p>Your WhoIsHiringInTech account has been created.</p><p>Please verify your email before signing in.</p>',
            'text_body': 'Hi {{ first_name|default:"there" }}, your WhoIsHiringInTech account has been created. Please verify your email before signing in.',
        },
        'email_verification': {
            'name': 'Verify email',
            'subject': 'Verify your WhoIsHiringInTech email',
            'html_body': '<p>Hi {{ first_name|default:"there" }},</p><p>Please verify your email address to activate your account.</p><p><a href="{{ verification_url }}">Verify email address</a></p>',
            'text_body': 'Verify your email address: {{ verification_url }}',
        },
        'password_reset': {
            'name': 'Password reset',
            'subject': 'Reset your WhoIsHiringInTech password',
            'html_body': '<p>Hi {{ first_name|default:"there" }},</p><p>Use this secure link to reset your password.</p><p><a href="{{ password_reset_url }}">Reset password</a></p><p>If you did not request this, you can ignore this email.</p>',
            'text_body': 'Reset your password: {{ password_reset_url }}',
        },
    }
    for key, values in templates.items():
        EmailTemplate.objects.get_or_create(key=key, defaults=values)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobpreference_actively_looking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('account_created', 'New account creation'), ('email_verification', 'Verify email'), ('password_reset', 'Password reset')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(help_text='Django template syntax is supported.')),
                ('text_body', models.TextField(blank=True, help_text='Optional plain-text version. Django template syntax is supported.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(create_default_email_templates, migrations.RunPython.noop),
    ]
