# Generated by Django 4.2.7 on 2026-02-13 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_add_homepage_sort_order_to_sitesettings'),
        ('recruiters', '0002_jobapplication_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Assign a company from the directory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_openings', to='companies.company'),
        ),
    ]
