#!/bin/bash

# Quick CORS Fix for Staging Server
# This script provides immediate commands to fix the staging server

echo "🚨 IMMEDIATE STAGING SERVER FIX"
echo "================================"
echo ""
echo "The issue: Frontend is calling PRODUCTION API instead of STAGING API"
echo "Root cause: VITE_API_URL environment variable not set on staging server"
echo ""

echo "🔧 QUICK FIX COMMANDS:"
echo "Copy and run these commands on your staging server:"
echo ""

echo "# 1. Connect to staging server"
echo "ssh root@45.79.211.144"
echo ""

echo "# 2. Navigate to project directory"
echo "cd /var/www/whit-release"
echo ""

echo "# 3. Create frontend environment file"
echo "cat > frontend/.env << 'EOF'"
echo "VITE_API_URL=https://staging.whoishiringintech.com/api"
echo "REACT_APP_API_URL=https://staging.whoishiringintech.com/api"
echo "EOF"
echo ""

echo "# 4. Rebuild frontend with correct API URL"
echo "cd frontend"
echo "export VITE_API_URL=https://staging.whoishiringintech.com/api"
echo "npm run build"
echo "cd .."
echo ""

echo "# 5. Update nginx configuration to handle CORS"
echo "cat > /etc/nginx/sites-available/whit-staging << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name staging.whoishiringintech.com 45.79.211.144;"
echo ""
echo "    location / {"
echo "        root /var/www/whit-release/frontend/dist;"
echo "        try_files \$uri \$uri/ /index.html;"
echo "    }"
echo ""
echo "    location /api/ {"
echo "        proxy_pass http://127.0.0.1:8000;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "        "
echo "        # CORS headers"
echo "        add_header Access-Control-Allow-Origin \"https://staging.whoishiringintech.com\" always;"
echo "        add_header Access-Control-Allow-Methods \"GET, POST, PUT, DELETE, OPTIONS, PATCH\" always;"
echo "        add_header Access-Control-Allow-Headers \"Authorization, Content-Type, Accept, X-Requested-With\" always;"
echo "        add_header Access-Control-Allow-Credentials \"true\" always;"
echo "        "
echo "        if (\$request_method = OPTIONS) {"
echo "            add_header Access-Control-Allow-Origin \"https://staging.whoishiringintech.com\";"
echo "            add_header Access-Control-Allow-Methods \"GET, POST, PUT, DELETE, OPTIONS, PATCH\";"
echo "            add_header Access-Control-Allow-Headers \"Authorization, Content-Type, Accept, X-Requested-With\";"
echo "            add_header Access-Control-Allow-Credentials \"true\";"
echo "            add_header Content-Length 0;"
echo "            add_header Content-Type text/plain;"
echo "            return 200;"
echo "        }"
echo "    }"
echo ""
echo "    location /media/ {"
echo "        alias /var/www/whit-release/backend/media/;"
echo "    }"
echo ""
echo "    location /static/ {"
echo "        alias /var/www/whit-release/backend/staticfiles/;"
echo "    }"
echo "}"
echo "EOF"
echo ""

echo "# 6. Enable the new nginx config"
echo "ln -sf /etc/nginx/sites-available/whit-staging /etc/nginx/sites-enabled/whit-staging"
echo "nginx -t"
echo "systemctl restart nginx"
echo ""

echo "# 7. Restart Django backend with correct CORS settings"
echo "cd backend"
echo "pkill -f 'manage.py runserver' || true"
echo "export CORS_ALLOWED_ORIGINS='https://staging.whoishiringintech.com,http://localhost:3000'"
echo "export ALLOWED_HOSTS='staging.whoishiringintech.com,45.79.211.144,localhost,127.0.0.1'"
echo "nohup python manage.py runserver 127.0.0.1:8000 > /var/log/whit-backend.log 2>&1 &"
echo "cd .."
echo ""

echo "# 8. Test the fix"
echo "curl -I https://staging.whoishiringintech.com/api/health/"
echo ""

echo "🎯 EXPECTED RESULT:"
echo "✅ Frontend will call staging.whoishiringintech.com/api instead of whoishiringintech.com/api"
echo "✅ CORS errors will disappear"
echo "✅ Companies will load successfully"
echo "✅ No more 'Failed to load companies' error"

echo ""
echo "📋 ALTERNATIVE: Run the automated fix script"
echo "scp fix-staging-cors.sh root@45.79.211.144:/tmp/"
echo "ssh root@45.79.211.144 'chmod +x /tmp/fix-staging-cors.sh && /tmp/fix-staging-cors.sh'"