# Generated by Django 4.2.7 on 2025-11-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='functions_text',
            field=models.TextField(blank=True, help_text='Legacy comma-separated list of functions'),
        ),
        migrations.AddField(
            model_name='function',
            name='color',
            field=models.CharField(default='#e3f2fd', help_text='Hex color code for the tag', max_length=7),
        ),
        migrations.AddField(
            model_name='function',
            name='text_color',
            field=models.CharField(default='#1976d2', help_text='Hex color code for the text', max_length=7),
        ),
        migrations.RemoveField(
            model_name='company',
            name='functions',
        ),
        migrations.AddField(
            model_name='company',
            name='functions',
            field=models.ManyToManyField(blank=True, related_name='companies', to='companies.function'),
        ),
    ]
