# Generated by Django 4.2.7 on 2025-11-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_functions_text_function_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(choices=[('slot1', 'Ad Slot 1 (After first 10 companies)'), ('slot2', 'Ad Slot 2 (After second 10 companies)')], max_length=20, unique=True)),
                ('ad_code', models.TextField(blank=True, help_text='Paste your Google AdSense or ad network code here')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Slot',
                'verbose_name_plural': 'Ad Slots',
                'ordering': ['slot_name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies_per_page', models.IntegerField(default=30, help_text='Number of companies to display per page')),
                ('companies_per_group', models.IntegerField(default=10, help_text='Number of companies in each group (between ad slots)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
