# Generated by Django 4.2.7 on 2025-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_adslot_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('login', 'Login Page'), ('register', 'Register Page')], max_length=20, unique=True)),
                ('form_position', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='Position of the form on the page', max_length=10)),
                ('side_heading', models.CharField(blank=True, help_text='Heading text for the opposite side', max_length=200)),
                ('side_subheading', models.CharField(blank=True, help_text='Subheading text for the opposite side', max_length=300)),
                ('side_text', models.TextField(blank=True, help_text='Additional text content for the opposite side')),
                ('side_image', models.FileField(blank=True, help_text='Image to display on the opposite side', null=True, upload_to='form_layouts/')),
                ('side_image_url', models.URLField(blank=True, help_text='Or use an external image URL', max_length=500, null=True)),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex color code for side panel background', max_length=7)),
                ('text_color', models.CharField(default='#000000', help_text='Hex color code for text', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form Layout',
                'verbose_name_plural': 'Form Layouts',
                'ordering': ['page_name'],
            },
        ),
    ]
