# Generated by Django 4.2.7 on 2025-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_formlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlayout',
            name='text_overlay_position',
            field=models.CharField(choices=[('top-left', 'Top Left'), ('top-center', 'Top Center'), ('top-right', 'Top Right'), ('center-left', 'Center Left'), ('center-center', 'Center Center'), ('center-right', 'Center Right'), ('bottom-left', 'Bottom Left'), ('bottom-center', 'Bottom Center'), ('bottom-right', 'Bottom Right')], default='center-center', help_text='Position of text overlay on the image', max_length=20),
        ),
    ]
