# Generated by Django 4.2.7 on 2025-11-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_formlayout_text_overlay_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlayout',
            name='side_heading_tag',
            field=models.CharField(choices=[('h1', 'H1 - Main Heading'), ('h2', 'H2 - Subheading'), ('h3', 'H3 - Subheading'), ('h4', 'H4 - Subheading'), ('h5', 'H5 - Subheading'), ('h6', 'H6 - Subheading'), ('p', 'P - Paragraph'), ('span', 'Span - Inline Text'), ('div', 'Div - Block Text')], default='h1', help_text='HTML tag for the heading', max_length=10),
        ),
        migrations.AddField(
            model_name='formlayout',
            name='side_subheading_tag',
            field=models.CharField(choices=[('h1', 'H1 - Main Heading'), ('h2', 'H2 - Subheading'), ('h3', 'H3 - Subheading'), ('h4', 'H4 - Subheading'), ('h5', 'H5 - Subheading'), ('h6', 'H6 - Subheading'), ('p', 'P - Paragraph'), ('span', 'Span - Inline Text'), ('div', 'Div - Block Text')], default='h2', help_text='HTML tag for the subheading', max_length=10),
        ),
        migrations.AddField(
            model_name='formlayout',
            name='side_text_tag',
            field=models.CharField(choices=[('h1', 'H1 - Main Heading'), ('h2', 'H2 - Subheading'), ('h3', 'H3 - Subheading'), ('h4', 'H4 - Subheading'), ('h5', 'H5 - Subheading'), ('h6', 'H6 - Subheading'), ('p', 'P - Paragraph'), ('span', 'Span - Inline Text'), ('div', 'Div - Block Text')], default='p', help_text='HTML tag for the text', max_length=10),
        ),
    ]
