# Generated by Django 4.2.7 on 2025-11-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_formlayout_side_heading_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='ad_type',
            field=models.CharField(choices=[('code', 'Ad Code (Google AdSense, etc.)'), ('image', 'Image Banner with Link')], default='code', help_text='Choose ad type: code or image banner', max_length=10),
        ),
        migrations.AddField(
            model_name='adslot',
            name='banner_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for banner image (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='adslot',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload banner image', null=True, upload_to='ad_banners/'),
        ),
        migrations.AddField(
            model_name='adslot',
            name='banner_link',
            field=models.URLField(blank=True, help_text='URL to redirect when banner is clicked', max_length=500),
        ),
        migrations.AddField(
            model_name='adslot',
            name='open_in_new_tab',
            field=models.BooleanField(default=True, help_text='Open banner link in new tab'),
        ),
    ]
