# Generated by Django 4.2.7 on 2025-11-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_adslot_ad_type_adslot_banner_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='label_size',
            field=models.CharField(choices=[('small', 'Small (0.5rem)'), ('medium', 'Medium (0.7rem)'), ('large', 'Large (0.9rem)'), ('extra-large', 'Extra Large (1.1rem)')], default='medium', help_text='Size of function and work environment labels', max_length=20),
        ),
    ]
