# Generated by Django 4.2.7 on 2026-02-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_sitesettings_label_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='mobile_banner_image',
            field=models.ImageField(blank=True, help_text='Upload mobile banner image (optional - will use desktop banner if not provided)', null=True, upload_to='ad_banners/'),
        ),
        migrations.AlterField(
            model_name='adslot',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload desktop banner image', null=True, upload_to='ad_banners/'),
        ),
    ]
