# Generated by Django 4.2.7 on 2026-02-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_adslot_mobile_banner_image_alter_adslot_banner_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-is_sponsored', 'sponsor_order', 'name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='is_sponsored',
            field=models.BooleanField(default=False, help_text='Mark as sponsored company'),
        ),
        migrations.AddField(
            model_name='company',
            name='sponsor_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for sponsored companies (lower numbers first)'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_sponsored', 'sponsor_order'], name='companies_c_is_spon_400db7_idx'),
        ),
    ]
