# Generated by Django 4.2.7 on 2026-02-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_company_options_company_is_sponsored_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload company logo image', null=True, upload_to='company_logos/'),
        ),
    ]
