# Generated by Django 4.2.7 on 2026-02-05 02:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0011_change_logo_to_imagefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name for internal tracking', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('priority', models.IntegerField(default=1, help_text='Higher numbers get more exposure', validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_impression_cap', models.IntegerField(help_text='Maximum impressions per day', validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_click_cap', models.IntegerField(blank=True, help_text='Optional daily click limit', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('targeting_countries', models.JSONField(blank=True, default=list, help_text='List of country codes. Empty = all countries')),
                ('targeting_functions', models.JSONField(blank=True, default=list, help_text='List of function names. Empty = all functions')),
                ('targeting_work_env', models.JSONField(blank=True, default=list, help_text='List of work environments. Empty = all')),
                ('bid_cpm', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per thousand impressions (optional)', max_digits=10, null=True)),
                ('weight', models.IntegerField(default=1, help_text='Weight for selection algorithm', validators=[django.core.validators.MinValueValidator(1)])),
                ('pacing', models.CharField(choices=[('even', 'Even Distribution'), ('asap', 'As Soon As Possible')], default='even', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_campaigns', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorStatsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_daily', to='companies.sponsorcampaign')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'date'], name='companies_s_campaig_30db26_idx')],
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SponsorImpressionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('page_url', models.URLField()),
                ('is_above_fold', models.BooleanField(default=False)),
                ('viewport_time_ms', models.IntegerField(blank=True, help_text='Time spent in viewport in milliseconds', null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_events', to='companies.sponsorcampaign')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'processed'], name='companies_s_created_f6800a_idx'), models.Index(fields=['campaign', 'user_hash'], name='companies_s_campaig_f8f823_idx')],
            },
        ),
        migrations.CreateModel(
            name='SponsorDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(db_index=True, help_text='Anonymized user identifier', max_length=64)),
                ('action', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], max_length=20)),
                ('page_key', models.CharField(help_text='Page context: browse:page=1:filters=hash', max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='companies.sponsorcampaign')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'user_hash', 'shown_at'], name='companies_s_campaig_7bd892_idx'), models.Index(fields=['user_hash', 'shown_at'], name='companies_s_user_ha_eef532_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sponsorcampaign',
            index=models.Index(fields=['status', 'start_at', 'end_at'], name='companies_s_status_a48ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcampaign',
            index=models.Index(fields=['company', 'status'], name='companies_s_company_28d65a_idx'),
        ),
    ]
