# Generated by Django 4.2.7 on 2026-02-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_add_sponsor_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Best-performing patterns for tools like yours', max_length=200)),
                ('subtitle', models.CharField(default='After a results preview, the best-performing sections are:', max_length=300)),
                ('section_header', models.CharField(default='Option A — How It Works (compact)', max_length=100)),
                ('description', models.CharField(default='This builds instant understanding + trust.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'How It Works Section',
                'verbose_name_plural': 'How It Works Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Are you hiring?', max_length=100)),
                ('description', models.TextField(default='Add your company and get discovered by candidates tracking active hiring signals.')),
                ('button_text', models.CharField(default='Add Company', max_length=50)),
                ('button_link', models.CharField(default='/add-company', help_text='Internal link or external URL', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=2, help_text='Display order on homepage')),
                ('background_color', models.CharField(default='#f8f9fa', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#212529', help_text='Hex color code', max_length=7)),
                ('button_color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recruiter Section',
                'verbose_name_plural': 'Recruiter Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('icon', models.CharField(default='🔍', help_text='Emoji or icon character', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='companies.howitworkssection')),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'ordering': ['section', 'order', 'step_number'],
            },
        ),
    ]
