# Generated by Django 4.2.7 on 2026-02-05 18:41

from django.db import migrations


def create_default_homepage_sections(apps, schema_editor):
    """Create default homepage sections and data"""
    HowItWorksSection = apps.get_model('companies', 'HowItWorksSection')
    HowItWorksStep = apps.get_model('companies', 'HowItWorksStep')
    RecruiterSection = apps.get_model('companies', 'RecruiterSection')
    
    # Create How It Works section
    how_it_works, created = HowItWorksSection.objects.get_or_create(
        title='Best-performing patterns for tools like yours',
        defaults={
            'subtitle': 'After a results preview, the best-performing sections are:',
            'section_header': 'Option A — How It Works (compact)',
            'description': 'This builds instant understanding + trust.',
            'is_active': True,
            'order': 1
        }
    )
    
    # Create steps
    if created:
        steps_data = [
            {'step_number': 1, 'icon': '1️⃣', 'title': 'We track companies', 'description': 'Monitor hiring activities across tech companies'},
            {'step_number': 2, 'icon': '2️⃣', 'title': 'We detect hiring signals', 'description': 'Identify active recruitment patterns and job postings'},
            {'step_number': 3, 'icon': '3️⃣', 'title': 'You discover who\'s actively hiring', 'description': 'Get matched with companies that fit your preferences'}
        ]
        
        for step_data in steps_data:
            HowItWorksStep.objects.create(
                section=how_it_works,
                step_number=step_data['step_number'],
                icon=step_data['icon'],
                title=step_data['title'],
                description=step_data['description'],
                is_active=True,
                order=step_data['step_number']
            )
    
    # Create Recruiter section
    RecruiterSection.objects.get_or_create(
        title='Are you hiring?',
        defaults={
            'description': 'Add your company and get discovered by candidates tracking active hiring signals.',
            'button_text': 'Add Company',
            'button_link': '/add-company',
            'is_active': True,
            'order': 2,
            'background_color': '#f8f9fa',
            'text_color': '#212529',
            'button_color': '#007bff'
        }
    )


def reverse_default_homepage_sections(apps, schema_editor):
    """Remove default homepage sections"""
    HowItWorksSection = apps.get_model('companies', 'HowItWorksSection')
    RecruiterSection = apps.get_model('companies', 'RecruiterSection')
    
    HowItWorksSection.objects.filter(title='Best-performing patterns for tools like yours').delete()
    RecruiterSection.objects.filter(title='Are you hiring?').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_howitworkssection_recruitersection_howitworksstep'),
    ]

    operations = [
        migrations.RunPython(
            create_default_homepage_sections,
            reverse_default_homepage_sections,
        ),
    ]