# Generated by Django 4.2.7 on 2026-02-09 01:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_add_recruiter_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyrecruiteraccess',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company Recruiter Access', 'verbose_name_plural': 'Company Recruiter Accesses'},
        ),
        migrations.AddField(
            model_name='companyrecruiteraccess',
            name='can_export_data',
            field=models.BooleanField(default=False, help_text='Can export campaign data'),
        ),
        migrations.AddField(
            model_name='companyrecruiteraccess',
            name='can_manage_campaigns',
            field=models.BooleanField(default=False, help_text='Can create and modify campaigns'),
        ),
        migrations.AddField(
            model_name='companyrecruiteraccess',
            name='can_view_analytics',
            field=models.BooleanField(default=True, help_text='Can view campaign analytics'),
        ),
        migrations.AlterField(
            model_name='companyrecruiteraccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'View Only'), ('manage', 'Manage Campaigns'), ('analytics', 'Analytics Only'), ('full', 'Full Access')], default='view', help_text='Level of access to company sponsor data', max_length=10),
        ),
        migrations.CreateModel(
            name='CampaignStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('job_page_clicks', models.PositiveIntegerField(default=0)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('application_clicks', models.PositiveIntegerField(default=0)),
                ('contact_clicks', models.PositiveIntegerField(default=0)),
                ('click_through_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_stats', to='companies.company')),
            ],
            options={
                'verbose_name': 'Campaign Statistics',
                'verbose_name_plural': 'Campaign Statistics',
                'ordering': ['-date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
