# Generated by Django 4.2.7 on 2026-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_alter_companyrecruiteraccess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlayout',
            name='image_width_percentage',
            field=models.IntegerField(choices=[(50, '50% - Equal Split'), (60, '60% Image / 40% Form'), (70, '70% Image / 30% Form'), (80, '80% Image / 20% Form'), (90, '90% Image / 10% Form')], default=50, help_text='Percentage of screen width the image/side panel should occupy'),
        ),
    ]
