# Generated by Django 4.2.7 on 2026-02-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_add_image_width_percentage_to_formlayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlayout',
            name='page_name',
            field=models.CharField(choices=[('login', 'Login Page'), ('register', 'Register Page'), ('recruiter_login', 'Recruiter Login Page'), ('recruiter_register', 'Recruiter Register Page')], max_length=30, unique=True),
        ),
    ]
