# Generated by Django 4.2.27 on 2026-02-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_add_recruiter_pages_to_formlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlayout',
            name='button_color',
            field=models.CharField(default='#6366f1', help_text='Hex color code for the form submit button (default: indigo #6366f1)', max_length=7),
        ),
    ]
