# Generated by Django 4.2.27 on 2026-02-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_add_button_color_to_formlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_companies',
            field=models.IntegerField(default=10, help_text='Number of companies to display on the homepage'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='companies_per_page',
            field=models.IntegerField(default=30, help_text='Number of companies to display per page on the All Companies listing page'),
        ),
    ]
