# Generated by Django 4.2.7 on 2026-02-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_add_homepage_companies_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_sort_order',
            field=models.CharField(choices=[('a-z', 'A-Z (Alphabetical)'), ('z-a', 'Z-A (Reverse Alphabetical)'), ('last-edited', 'Last Edited First'), ('random', 'Random')], default='a-z', help_text='Sort order of companies on the homepage', max_length=20),
        ),
    ]
