# Generated by Django 4.2.7 on 2026-02-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_add_homepage_sort_order_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='jobs_per_page',
            field=models.IntegerField(default=20, help_text='Number of job openings to display per page on the Jobs listing page'),
        ),
    ]
